import firebase from "firebase/compat";
import Timestamp = firebase.firestore.Timestamp;

export enum TodoPriority {
  LOW = 1,
  MEDIUM = 2,
  HIGH = 3,
}

export interface Todo {
  id?: string; // Must be autogenerated by Firebase
  text: string;
  completed: boolean;
  author: string;
  priority: TodoPriority;
  timestamp: Timestamp;
}
