import firebase from "firebase/compat";
import Timestamp = firebase.firestore.Timestamp;
import { FiretuUser } from "../recoil/userState";

/**
 * Todo priority enum (1 = LOW, 2 = MEDIUM, 3 = HIGH)
 */
export enum TodoPriority {
  LOW = 1,
  MEDIUM = 2,
  HIGH = 3,
}

/**
 * Todo interface (should be the same as the Firestore collection)
 * @param id The id of the todo item (MUST be autogenerated by Firebase)
 * @param text The text of the todo item
 * @param completed Whether the todo item is completed or not
 * @param author The author of the todo item (uid only)
 * @param priority The priority of the todo item (1 = LOW, 2 = MEDIUM, 3 = HIGH)
 * @param timestamp The timestamp of the todo item
 */
export interface Todo {
  id?: string;
  text: string;
  completed: boolean;
  author: Pick<FiretuUser, "uid">;
  priority: TodoPriority;
  timestamp: Timestamp;
}
